apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
#    tags.datadoghq.com/env: dev
#    tags.datadoghq.com/service: spring-boot-app
#    tags.datadoghq.com/version: v1.28.0    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
  #      tags.datadoghq.com/env: dev
  #      tags.datadoghq.com/service: spring-boot-app
  #      tags.datadoghq.com/version: v1.28.0
  #      admission.datadoghq.com/enabled: "true"
  #    annotations:
   #     admission.datadoghq.com/java-lib.version: v1.28.0        
    spec:
      containers:
      - name: spring-boot-app
        image: vipulk772/cicd:1
  #      env:
 #         - name: DD_LOGS_INJECTION
  #          value: "true"
        ports:
        - containerPort: 8080
